baseURL = "http://www.siete3.com/"
languageCode = "en-US"
title = "Siete3.com"
theme = "minimal"
# theme = "hyde"
disqusShortname = "siete3-com" # delete this to disable disqus comments
googleAnalytics = ""

# sectionPagesMenu = "main"


[markup.goldmark.renderer]
unsafe= true

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    author = "Rodrigo Erades"
    description = "Personal blog about programming mostly with JavaScript"
    githubUsername = "area73"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 10

[[menu.main]]
    identifier = "posts"
    url = "/posts/"
    name = "Posts"
    weight = 20

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:rerades@siete3.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/area73/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/area_73/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/siete3/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/2521616/boogie"
    name = "stack-overflow"
    weight = 5
