baseURL = "http://www.siete3.com/"
languageCode = "es-es"
title = "Siete3.com -- Hugo Minimal"
theme = "minimal"
disqusShortname = "@area73" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Rodrigo Erades"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "area73"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift","javascript","css","SCSS"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:rerades@siete3.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/area73/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/area_73/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/siete3/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/2521616/boogie"
    name = "stack-overflow"
    weight = 5
